caractere = input("Digite um caractere:")

print(f"O caractere {caractere} é isalpha: {caractere.isalpha()}")
print(f"O caractere {caractere} é isdecimal: {caractere.isdecimal()}")
print(f"O caractere {caractere} é isdigit: {caractere.isdigit()}")
print(f"O caractere {caractere} é isidentifier: {caractere.isidentifier()}")
print(f"O caractere {caractere} é islower: {caractere.islower()}")
print(f"O caractere {caractere} é isnumeric: {caractere.isnumeric()}")
print(f"O caractere {caractere} é isprintable: {caractere.isprintable()}")
print(f"O caractere {caractere} é isspace: {caractere.isspace()}")
print(f"O caractere {caractere} é istitle: {caractere.istitle()}")
print(f"O caractere {caractere} é isupper: {caractere.isupper()}")
print(f"O caractere {caractere} é alfanumerico: {(caractere.isalnum())}")
print(f"O caractere {caractere} é decimal: {(caractere.isdecimal())}")
